import {test} from 'node:test';
import assert from 'node:assert/strict';
import {api} from './api';
import {localDatabase} from './local-db';
function fixture(){const DB=localDatabase(true);return async(path:string,data?:unknown,owner?:string,cookie?:string)=>{const headers:Record<string,string>={};if(owner)headers['oai-authenticated-user-id']=owner;if(cookie)headers.cookie=cookie;const response=await api(new Request('https://quiz.test/api'+path,{method:data===undefined?'GET':'POST',headers,body:data===undefined?undefined:JSON.stringify(data)}),{DB});return {status:response.status,body:await response.json() as any,cookie:response.headers.get('set-cookie')?.split(';')[0]}}}
async function setup(){const call=fixture();const made=await call('/events',{title:'検証イベント'},'host');assert.equal(made.status,201);const id=made.body.id;return {call,id,p:`/events/${id}`}}
test('owner-only aggregation, anonymous participation and no result leaks',async()=>{const {call,p}=await setup();assert.equal((await call(p+'/host')).status,401);assert.equal((await call(p+'/host',undefined,'other')).status,403);assert.equal((await call(p+'/control',{command:'start',current:0},'other')).status,403);const publicState=await call(p+'/state');assert.deepEqual(Object.keys(publicState.body).sort(),['answer','event','group','question']);assert.equal(publicState.body.event.owner,undefined);assert.equal((await call('/events',undefined,'other')).body.length,0)});
test('unique normalized group names, existing cookie recovery, forged cookie rejected',async()=>{const {call,p,id}=await setup();const first=await call(p+'/join',{name:'チームＡ'});assert.equal(first.status,201);assert.ok(first.cookie);assert.equal((await call(p+'/join',{name:'チームA'})).status,409);const repeated=await call(p+'/join',{name:'別名'},undefined,first.cookie);assert.equal(repeated.body.group.id,first.body.group.id);assert.equal((await call(p+'/state',undefined,undefined,first.cookie)).body.group.name,'チームA');assert.equal((await call(p+'/answer',{number:1,choice:'o'},undefined,`mq_${id}=fake`)).status,401)});
test('start without question text, ten questions, immutable answers, retries, closure, next question and finish',async()=>{const {call,p}=await setup();const a=await call(p+'/join',{name:'A'}),b=await call(p+'/join',{name:'B'});assert.equal((await call(p+'/answer',{number:1,choice:'o'},undefined,a.cookie)).status,409);assert.equal((await call(p+'/control',{command:'start',current:0},'host')).status,200);assert.equal((await call(p+'/state')).body.question.number,1);assert.equal((await call(p+'/state')).body.question.body,undefined);assert.equal((await call(p+'/host',undefined,'host')).body.questions[0].body,undefined);assert.equal((await call(p+'/control',{command:'start',current:1},'host')).status,409);
 const results=await Promise.all(['o','x'].map(choice=>call(p+'/answer',{number:1,choice},undefined,a.cookie)));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const saved=(await call(p+'/state',undefined,undefined,a.cookie)).body.answer;assert.equal((await call(p+'/answer',{number:1,choice:saved},undefined,a.cookie)).status,200);assert.equal((await call(p+'/control',{command:'next',current:1},'host')).status,409);assert.equal((await call(p+'/control',{command:'close',current:1},'host')).status,200);assert.equal((await call(p+'/answer',{number:1,choice:'x'},undefined,b.cookie)).status,409);const stats=(await call(p+'/host',undefined,'host')).body;assert.equal(stats.totals.o+stats.totals.x,1);assert.equal(stats.totals.pending,1);
 for(let current=1;current<10;current++){assert.equal((await call(p+'/control',{command:'next',current},'host')).status,200);assert.equal((await call(p+'/answer',{number:current+1,choice:'x'},undefined,a.cookie)).status,200);assert.equal((await call(p+'/answer',{number:current,choice:'o'},undefined,b.cookie)).status,409);assert.equal((await call(p+'/control',{command:'close',current:current+1},'host')).status,200)}assert.equal((await call(p+'/control',{command:'next',current:10},'host')).status,409);assert.equal((await call(p+'/control',{command:'finish',current:10},'host')).status,200);assert.equal((await call(p+'/join',{name:'C'})).status,409);assert.equal((await call(p+'/state',undefined,undefined,a.cookie)).body.event.phase,'finished');
});
test('cross-event credentials cannot submit answers',async()=>{const {call,p}=await setup();const a=await call(p+'/join',{name:'A'});const another=(await call('/events',{title:'他のイベント'},'host')).body.id;assert.equal((await call(`/events/${another}/answer`,{number:1,choice:'o'},undefined,a.cookie)).status,401)});
