<script lang="ts">
 import { onMount } from 'svelte';
 import QRCode from 'qrcode';
 import { request,message,hostPasswordKey } from './api';
 import type { HostState,QuizEvent,Choice } from './types';
 let {id}:{id:string}=$props();
 const appBase=import.meta.env.BASE_URL,hostHome=appBase+'?host=1';
 let events=$state<QuizEvent[]>([]),title=$state('みんなで ○×クイズ'),questionCount=$state(10),quiz=$state<HostState|null>(null),tab=$state<'live'|'qr'>('live'),error=$state(''),notice=$state(''),busy=$state(false),qr=$state(''),confirmClose=$state(false),deleteTarget=$state<QuizEvent|null>(null),polling=false,authenticated=$state(false),password=$state(''),draftAnswers=$state<(Choice|null)[]>([]),keyDirty=$state(false);
 const invite=$derived(typeof location!=='undefined'?`${location.origin}${appBase}?e=${id}`:'');
 let closeDialog=$state<HTMLDialogElement>();
 let deleteDialog=$state<HTMLDialogElement>();
 $effect(()=>{if(confirmClose)closeDialog?.showModal();else closeDialog?.close()});
 $effect(()=>{if(deleteTarget&&!deleteDialog?.open)deleteDialog?.showModal();else if(!deleteTarget&&deleteDialog?.open)deleteDialog.close()});
 const labels:Record<string,string>={setup:'開始前',open:'回答受付中',closed:'回答締め切り',finished:'終了'};
 async function refresh(){if(polling)return;polling=true;try{if(id){quiz=await request<HostState>(`/api/events/${id}/host`);if(quiz.event.phase==='setup'&&!keyDirty)draftAnswers=quiz.questions.map(q=>q.correctChoice??null);}else events=await request<QuizEvent[]>('/api/events');authenticated=true;error=''}catch(e){authenticated=false;error=message(e)}finally{polling=false}}
 async function login(){busy=true;error='';sessionStorage.setItem(hostPasswordKey,password);await refresh();if(!authenticated)sessionStorage.removeItem(hostPasswordKey);password='';busy=false}
 async function create(){busy=true;error='';try{const event=await request<{id:string}>('/api/events',{title,questionCount});location.href=hostHome+'&e='+event.id}catch(e){error=message(e)}finally{busy=false}}
 async function deleteEvent(){const target=deleteTarget;if(!target||busy)return;busy=true;error='';notice='';try{await request(`/api/events/${target.id}/delete`,{});events=events.filter(event=>event.id!==target.id);deleteTarget=null;notice=`「${target.title}」を削除しました。`}catch(e){error=message(e)}finally{busy=false}}
 async function saveKey(){if(!quiz||draftAnswers.some(choice=>!choice))return;busy=true;error='';notice='';try{await request(`/api/events/${id}/key`,{choices:draftAnswers});keyDirty=false;await refresh();notice='正解を保存しました。'}catch(e){error=message(e)}finally{busy=false}}
 async function control(command:string){if(!quiz)return;busy=true;error='';notice='';confirmClose=false;try{await request(`/api/events/${id}/control`,{command,current:quiz.event.current});await refresh();tab='live'}catch(e){error=message(e);await refresh()}finally{busy=false}}
 function rankAt(index:number){if(!quiz)return index+1;const score=quiz.groups[index]?.correctCount;return quiz.groups.findIndex(group=>group.correctCount===score)+1}
 async function copy(){try{await navigator.clipboard.writeText(invite);notice='参加URLをコピーしました。'}catch{error='コピーできませんでした。表示されているURLを選択してコピーしてください。'}}
 onMount(()=>{void(async()=>{try{if(sessionStorage.getItem(hostPasswordKey))await refresh();if(id)qr=await QRCode.toDataURL(invite,{width:440,margin:2,color:{dark:'#172c48',light:'#ffffff'},errorCorrectionLevel:'M'})}catch(e){error=message(e)}})();const timer=setInterval(()=>{if(id&&authenticated&&!busy&&!document.hidden)void refresh()},2500);return()=>clearInterval(timer)});
</script>
<main class="host-main">
 <div class="host-breadcrumb"><a href={hostHome}>司会者画面</a>{#if id}<span>/</span><span>イベント管理</span>{/if}<span class="private-badge">司会者のみ</span></div>
 {#if error}<p class="error" role="alert">{error}{#if authenticated} <button class="inline-button" onclick={()=>{error='';void refresh()}}>再読み込み</button>{/if}</p>{/if}
 {#if notice}<p class="success" role="status">{notice}</p>{/if}
 {#if !authenticated}
  <section class="card login-card"><h1>司会者用パスワード</h1><form onsubmit={(e)=>{e.preventDefault();void login()}}><label for="host-password">パスワード</label><input id="host-password" type="password" bind:value={password} autocomplete="current-password" required/><button class="primary" disabled={busy||!password}>{busy?'確認中…':'司会者ページに入る'} <span>→</span></button></form></section>
 {:else if !id}
  <div class="host-home-grid"><section class="card"><div class="section-kicker">新しいイベント</div><h2>イベントを作成する</h2><form onsubmit={(e)=>{e.preventDefault();void create()}}><label for="event-title">イベント名</label><input id="event-title" bind:value={title} maxlength="80" required/><label for="question-count">問題数</label><select id="question-count" bind:value={questionCount}>{#each Array.from({length:30},(_,i)=>i+1) as count}<option value={count}>{count}問</option>{/each}</select><button class="primary" disabled={busy||!title.trim()}>{busy?'作成中…':'イベントを作成'} <span>→</span></button></form></section>
  <section class="card"><div class="section-kicker">作成済みのイベント</div><h2>イベントを開く</h2>{#if events.length===0}<div class="empty-state">まだイベントはありません。<br/>左のフォームから作成してください。</div>{:else}<div class="event-list">{#each events as event (event.id)}<div class="event-row"><a href={hostHome+'&e='+event.id}><strong>{event.title}</strong><span>{labels[event.phase]}　→</span></a><button class="event-delete" type="button" aria-label={`「${event.title}」を削除`} disabled={busy} onclick={()=>deleteTarget=event}>削除</button></div>{/each}</div>{/if}</section></div>
 {:else if quiz}
  <div class="page-heading"><div><div class="eyebrow">HOST CONSOLE</div><h1>{quiz.event.title}</h1></div><span class="pill phase" class:is-open={quiz.event.phase==='open'}>{labels[quiz.event.phase]}</span></div>
  <nav class="tabs" aria-label="イベント管理"><button class:active={tab==='live'} onclick={()=>tab='live'}>進行と集計</button><button class:active={tab==='qr'} onclick={()=>tab='qr'}>参加用QRコード</button></nav>
  {#if tab==='qr'}
   <section class="card qr-card"><div><div class="section-kicker">参加者へのご案内</div><h2>代表者1名が読み取ってください</h2><p class="muted">グループごとに1台の端末で参加します。<br/>このQRコードを会場の画面に表示するか、印刷して配布してください。</p><label for="invite-url">参加URL</label><input id="invite-url" value={invite} readonly onclick={(e)=>e.currentTarget.select()}/><div class="button-row"><button class="secondary" onclick={copy}>URLをコピー</button>{#if qr}<a class="secondary" href={qr} download="quiz-qr.png">QR画像を保存</a>{/if}</div><div class="note">参加コード：<code>{id}</code></div>{#if location.hostname==='127.0.0.1'||location.hostname==='localhost'}<div class="notice">このQRコードは開発用です。会場では公開先のURLで表示したQRコードを使用してください。</div>{/if}</div><div class="qr-frame">{#if qr}<img src={qr} alt="グループ登録画面への参加用QRコード" width="280" height="280"/>{:else}<p>QRコードを準備中…</p>{/if}<strong>みんなで ○×クイズ</strong><span>グループの代表者が読み取り</span></div></section>
  {:else}
   <div class="host-dashboard"><div class="host-primary"><section class="card control-card"><div class="question-meta"><span class="section-kicker">いまの問題</span><span class="pill">{quiz.event.current===0&&quiz.event.phase!=='setup'?'例題':`${quiz.event.current} / ${quiz.event.questionCount} 問`}</span></div>
    {#if quiz.event.phase==='setup'}<h2>参加者がそろったら、スタート</h2><p class="muted">参加用QRコードを配布し、グループ登録を確認してください。問題は司会者が会場で出題します。</p><div class="button-row"><button class="secondary" disabled={busy||keyDirty||quiz.questions.some(q=>!q.correctChoice)} onclick={()=>control('sample')}>例題を開始する</button><button class="primary" disabled={busy||keyDirty||quiz.questions.some(q=>!q.correctChoice)} onclick={()=>control('start')}>第1問を開始する <span>→</span></button></div><p class="note">例題は任意です。回答できますが、正解数には含まれません。</p>
    {:else if quiz.event.phase==='finished'}<div class="completed-heading"><div class="eyebrow">ALL QUESTIONS COMPLETED</div><h2>全{quiz.event.questionCount}問、終了しました</h2><p class="muted">チームごとの最終正解数を表示しています。</p></div>
    {:else}<div class="host-question"><h2>{quiz.event.current===0?'例題':`第${quiz.event.current}問`}</h2></div>
      {#if quiz.event.phase==='open'}<button class="danger" disabled={busy} onclick={()=>confirmClose=true}>回答を締め切る</button><p class="note">締め切ると、未回答のグループも送信できなくなります。</p>
      {:else}<div class="notice">回答を締め切りました。グループに○×の札を上げてもらいましょう。</div><button class="primary" disabled={busy} onclick={()=>control(quiz!.event.current===0?'start':quiz!.event.current===quiz!.event.questionCount?'finish':'next')}>{quiz.event.current===0?'第1問を開始する':quiz.event.current===quiz.event.questionCount?'クイズを終了する':`第${quiz.event.current+1}問を開始する`} <span>→</span></button>{/if}
    {/if}</section>
    {#if quiz.event.phase==='setup'}<section class="card answer-key-editor"><h2>正解の設定</h2><p class="muted">各問の正解を選んで保存してください。全問の正解を保存すると開始できます。</p><div class="answer-key-grid">{#each quiz.questions as question,i}<div class="answer-key-row"><strong>第{question.number}問</strong><div class="answer-key-options" role="group" aria-label={`第${question.number}問の正解`}><button type="button" class:chosen={draftAnswers[i]==='o'} aria-pressed={draftAnswers[i]==='o'} onclick={()=>{draftAnswers[i]='o';keyDirty=true}}>○</button><button type="button" class:chosen={draftAnswers[i]==='x'} aria-pressed={draftAnswers[i]==='x'} onclick={()=>{draftAnswers[i]='x';keyDirty=true}}>×</button></div></div>{/each}</div><button class="primary" disabled={busy||draftAnswers.length!==quiz.event.questionCount||draftAnswers.some(choice=>!choice)} onclick={saveKey}>正解を保存する</button></section>{/if}
    {#if quiz.event.phase!=='finished'}<section class="card results-card"><div class="result-title"><h2>回答の集計</h2><span class="section-kicker">司会者だけに表示 · 自動更新</span></div><div class="stat-grid"><div class="stat stat-o"><span>○ を選択</span><strong>{quiz.totals.o}<small>グループ</small></strong></div><div class="stat stat-x"><span>× を選択</span><strong>{quiz.totals.x}<small>グループ</small></strong></div><div class="stat"><span>未回答</span><strong>{quiz.totals.pending}<small>グループ</small></strong></div></div><div class="answer-bar" aria-label={`○ ${quiz.totals.o}、× ${quiz.totals.x}、未回答 ${quiz.totals.pending}`}><span class="bar-o" style:width={(quiz.totals.o/(quiz.groups.length||1)*100)+'%'}></span><span class="bar-x" style:width={(quiz.totals.x/(quiz.groups.length||1)*100)+'%'}></span></div><p class="note">決定済み {quiz.totals.o+quiz.totals.x} / {quiz.groups.length} グループ</p></section>{/if}</div>
    <aside class="card groups-card"><div class="result-title"><h2>{quiz.event.phase==='finished'?'チーム別正解数':'参加グループ'}</h2><span class="count">{quiz.groups.length}</span></div>{#if quiz.groups.length===0}<div class="empty-state">参加グループを待っています。<br/>QRコードを配布してください。</div><button class="secondary full" onclick={()=>tab='qr'}>参加用QRコードを開く</button>{:else}<ul class="group-list">{#each quiz.groups as group,i}<li class:score-row={quiz.event.phase==='finished'}>{#if quiz.event.phase==='finished'}<span class="rank">{rankAt(i)}位</span>{/if}<span>{group.name}</span><strong class:score={quiz.event.phase==='finished'} class:group-o={quiz.event.phase!=='finished'&&group.choice==='o'} class:group-x={quiz.event.phase!=='finished'&&group.choice==='x'}>{quiz.event.phase==='finished'?`${group.correctCount ?? 0} / ${quiz.event.questionCount}問`:group.choice==='o'?'○':group.choice==='x'?'×':quiz.event.phase==='setup'?'登録済み':'未回答'}</strong></li>{/each}</ul>{/if}</aside>
   </div>
  {/if}
 {/if}
</main>
<dialog bind:this={closeDialog} class="modal card" aria-labelledby="close-heading" oncancel={()=>confirmClose=false}>{#if quiz}<h2 id="close-heading">回答を締め切りますか？</h2><p>未回答のグループは <strong>{quiz.totals.pending}組</strong> です。<br/>締め切り後は回答を受け付けません。</p><div class="button-row"><button class="secondary" onclick={()=>confirmClose=false}>戻る</button><button class="danger" onclick={()=>control('close')}>締め切る</button></div>{/if}</dialog>
<dialog bind:this={deleteDialog} class="modal card" aria-labelledby="delete-heading" oncancel={()=>deleteTarget=null}>{#if deleteTarget}<h2 id="delete-heading">「{deleteTarget.title}」を削除しますか？</h2><p>参加グループ、回答、正解の設定も削除されます。この操作は取り消せません。</p><div class="button-row"><button class="secondary" disabled={busy} onclick={()=>deleteTarget=null}>戻る</button><button class="danger" disabled={busy} onclick={deleteEvent}>{busy?'削除中…':'削除する'}</button></div>{/if}</dialog>
